name: Compilar mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8

      - name: Compilar
        run: gradle build

      - name: Subir el jar
        uses: actions/upload-artifact@v4
        with:
          name: otraventana-jar
          path: build/libs/otraventana-1.0.0.jar
